version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.5
    container_name: keycloak
    restart: always
    ports:
      - "8090:8090"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: http://keycloak:8090/
      KC_HOSTNAME_BACKCHANNEL_DYNAMIC: true
    command: start-dev --http-port=8090
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      - local

networks:
  local:
    driver: bridge
    external: true

volumes:
  keycloak_data:
    driver: local