spring:
  datasource:
    livoltek:
      url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/livoltek
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  info.env.enabled: true
  endpoints.web.exposure.include: '*'

jwt:
  auth:
    converter:
      resource-id: livoltek
      principal-attribute: preferred_username

keycloak:
  grant_type: client_credentials
  client_id: livoltek
  client_secret: p3gWEMohIj1NKTBMwvSokHsspFtrKiOL
  url-token-client-secret: http://localhost:8090/realms/livoltek/protocol/openid-connect/token
  url-end-point-users: http://localhost:8090/admin/realms/livoltek/users
  url-endpoint-add-user-role: http://localhost:8090/admin/realms/livoltek/users/usuarioIdKeycloak/role-mappings/realm
  defaultPassword: Mudar@123